// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtWIw4HLKFvuyYiP-z0ltvcnA5cPp0mhU',
    appId: '1:369464772062:web:23aa3789d52c9c8bcac94f',
    messagingSenderId: '369464772062',
    projectId: 'unmissable-73087',
    authDomain: 'unmissable-73087.firebaseapp.com',
    storageBucket: 'unmissable-73087.appspot.com',
    measurementId: 'G-JB1NSJ7V0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVKrxn3aPwGUssYnKMO-yvaMXaicHzK7M',
    appId: '1:369464772062:android:b93bd33b42e6277acac94f',
    messagingSenderId: '369464772062',
    projectId: 'unmissable-73087',
    storageBucket: 'unmissable-73087.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZwHGgIAoNexQQRaoHU7o9HyqM8IK5l2g',
    appId: '1:369464772062:ios:d527d6a6a1c15855cac94f',
    messagingSenderId: '369464772062',
    projectId: 'unmissable-73087',
    storageBucket: 'unmissable-73087.appspot.com',
    iosBundleId: 'com.example.unmissable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZwHGgIAoNexQQRaoHU7o9HyqM8IK5l2g',
    appId: '1:369464772062:ios:71e205297b92a2e7cac94f',
    messagingSenderId: '369464772062',
    projectId: 'unmissable-73087',
    storageBucket: 'unmissable-73087.appspot.com',
    iosBundleId: 'com.example.unmissable.RunnerTests',
  );
}
